"""Add phone_number and profile_picture_url to users

Revision ID: a76451afd578
Revises: d3c1da176685
Create Date: 2025-10-23 21:26:00.328447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a76451afd578'
down_revision: Union[str, None] = 'd3c1da176685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: Removidas las líneas que eliminaban sensor_catalog (error de auto-generación)
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True, comment='Número de teléfono para notificaciones Telegram'))
    op.add_column('users', sa.Column('profile_picture_url', sa.String(length=512), nullable=True, comment='URL de la foto de perfil del usuario'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTA: Removidas las líneas que recreaban sensor_catalog (error de auto-generación)
    op.drop_column('users', 'profile_picture_url')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
