"""Add timezone to locations, deleted_device_name to readings, archived fields to users

Revision ID: 8c2693032cad
Revises: 5494f0ce411a
Create Date: 2025-10-21 20:18:52.401116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2693032cad'
down_revision: Union[str, None] = '5494f0ce411a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Agregar timezone como nullable primero
    op.add_column('locations', sa.Column('timezone', sa.String(length=50), nullable=True, comment='Zona horaria de la ubicación (ej: America/Argentina/Buenos_Aires)'))
    # Actualizar valores existentes a 'UTC'
    op.execute("UPDATE locations SET timezone = 'UTC' WHERE timezone IS NULL")
    # Ahora hacer NOT NULL
    op.alter_column('locations', 'timezone', nullable=False)
    op.add_column('sensor_readings', sa.Column('deleted_device_name', sa.String(length=255), nullable=True, comment="Nombre del device eliminado (ej: 'Dispositivo Eliminado el 21/10/2025')"))
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='ID del device que generó esta lectura (NULL si fue eliminado)',
               existing_comment='ID del device que generó esta lectura')
    op.drop_constraint('sensor_readings_device_id_fkey', 'sensor_readings', type_='foreignkey')
    op.create_foreign_key(None, 'sensor_readings', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    # Agregar archived como nullable primero
    op.add_column('users', sa.Column('archived', sa.Boolean(), nullable=True, comment='Indica si el usuario está archivado (soft delete adicional)'))
    # Actualizar valores existentes a False
    op.execute("UPDATE users SET archived = FALSE WHERE archived IS NULL")
    # Ahora hacer NOT NULL
    op.alter_column('users', 'archived', nullable=False)
    op.add_column('users', sa.Column('archived_at', sa.DateTime(), nullable=True, comment='Fecha en que el usuario fue archivado'))
    op.create_index(op.f('ix_users_archived'), 'users', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_archived'), table_name='users')
    op.drop_column('users', 'archived_at')
    op.drop_column('users', 'archived')
    op.drop_constraint(None, 'sensor_readings', type_='foreignkey')
    op.create_foreign_key('sensor_readings_device_id_fkey', 'sensor_readings', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.alter_column('sensor_readings', 'device_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='ID del device que generó esta lectura',
               existing_comment='ID del device que generó esta lectura (NULL si fue eliminado)')
    op.drop_column('sensor_readings', 'deleted_device_name')
    op.drop_column('locations', 'timezone')
    # ### end Alembic commands ###
