"""add_audit_log_table

Revision ID: 25ecdcad99e4
Revises: a76451afd578
Create Date: 2025-10-29 22:58:01.344218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25ecdcad99e4'
down_revision: Union[str, None] = 'a76451afd578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # NO eliminar sensor_catalog - solo comentamos para mantener tabla existente
    # op.drop_index('idx_sensor_catalog_active', table_name='sensor_catalog')
    # op.drop_index('idx_sensor_catalog_protocol', table_name='sensor_catalog')
    # op.drop_index('idx_sensor_catalog_type', table_name='sensor_catalog')
    # op.drop_index('ix_sensor_catalog_id', table_name='sensor_catalog')
    # op.drop_table('sensor_catalog')

    # Crear tabla audit_log para compliance (IEC 62443, FDA 21 CFR Part 11)
    op.create_table(
        'audit_log',
        sa.Column('id', sa.BigInteger(), nullable=False, comment='ID autoincremental (BIGINT para millones de registros)'),
        sa.Column('user_id', sa.Integer(), nullable=True, comment='ID del usuario (NULL si acción de sistema)'),
        sa.Column('user_role', sa.String(length=32), nullable=True, comment='Rol del usuario al momento de la acción'),
        sa.Column('device_id', sa.Integer(), nullable=True, comment='ID del device relacionado (NULL si no aplica)'),
        sa.Column('action_type', sa.String(length=64), nullable=False, comment='Tipo de acción (USER_LOGIN, DEVICE_CREATED, etc)'),
        sa.Column('entity_type', sa.String(length=32), nullable=True, comment='Tipo de entidad afectada (user, device, alert_rule)'),
        sa.Column('entity_id', sa.Integer(), nullable=True, comment='ID de la entidad afectada'),
        sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Cambios: {"before": {...}, "after": {...}}'),
        sa.Column('ip_address', postgresql.INET(), nullable=True, comment='Dirección IP de origen'),
        sa.Column('user_agent', sa.Text(), nullable=True, comment='User-Agent del navegador'),
        sa.Column('timestamp', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp UTC (generado por DB)'),
        sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Metadata adicional'),
        sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )

    # Índices para queries frecuentes
    op.create_index('idx_audit_log_id', 'audit_log', ['id'])
    op.create_index('idx_audit_log_user_id', 'audit_log', ['user_id'])
    op.create_index('idx_audit_log_device_id', 'audit_log', ['device_id'])
    op.create_index('idx_audit_log_action_type', 'audit_log', ['action_type'])
    op.create_index('idx_audit_log_timestamp', 'audit_log', ['timestamp'], postgresql_using='btree')
    op.create_index('idx_audit_log_entity', 'audit_log', ['entity_type', 'entity_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Eliminar tabla audit_log
    op.drop_index('idx_audit_log_entity', table_name='audit_log')
    op.drop_index('idx_audit_log_timestamp', table_name='audit_log')
    op.drop_index('idx_audit_log_action_type', table_name='audit_log')
    op.drop_index('idx_audit_log_device_id', table_name='audit_log')
    op.drop_index('idx_audit_log_user_id', table_name='audit_log')
    op.drop_index('idx_audit_log_id', table_name='audit_log')
    op.drop_table('audit_log')

    # ### end Alembic commands ###
