"""Add password_reset_tokens table

Revision ID: 7434c05be701
Revises: 8c2693032cad
Create Date: 2025-10-21 20:29:54.388727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7434c05be701'
down_revision: Union[str, None] = '8c2693032cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='ID del usuario que solicita el reset'),
    sa.Column('token', sa.String(length=255), nullable=False, comment='Token único UUID para validación'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Fecha de expiración del token (10 minutos desde creación)'),
    sa.Column('used', sa.Boolean(), nullable=False, comment='Indica si el token ya fue utilizado'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación del token'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_password_reset_token', 'password_reset_tokens', ['token'], unique=False)
    op.create_index('idx_password_reset_used', 'password_reset_tokens', ['used'], unique=False)
    op.create_index('idx_password_reset_user', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_id'), 'password_reset_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_used'), 'password_reset_tokens', ['used'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_used'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_id'), table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_user', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_used', table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_token', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
