"""add api_key and api_key_encrypted columns to devices

Revision ID: 035e1efdb618
Revises: 25ecdcad99e4
Create Date: 2025-11-08 22:57:48.285567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '035e1efdb618'
down_revision: Union[str, None] = '25ecdcad99e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - CORREGIDO MANUALMENTE ###
    # Solo agregar columnas de API key, NO eliminar otras tablas
    op.add_column('devices', sa.Column('api_key', sa.String(length=255), nullable=True, comment='API Key en texto plano (DEPRECATED - usar api_key_encrypted)'))
    op.add_column('devices', sa.Column('api_key_encrypted', sa.Text(), nullable=True, comment='API Key encriptada con Fernet (AES-128 CBC + HMAC SHA256)'))
    op.create_index(op.f('ix_devices_api_key'), 'devices', ['api_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - CORREGIDO MANUALMENTE ###
    # Solo eliminar columnas de API key, NO recrear otras tablas
    op.drop_index(op.f('ix_devices_api_key'), table_name='devices')
    op.drop_column('devices', 'api_key_encrypted')
    op.drop_column('devices', 'api_key')
    # ### end Alembic commands ###
